root: true
env:
  browser: true
  es2021: true
  node: true
  jest: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {
  indent: ['error', 4],
  import/extensions: 'off',
  import/prefer-default-export: 'off',
  no-plusplus: 'off',
  no-unused-vars: 'off',
  '@typescript-eslint/no-unused-vars': 'error'
}
settings:
    import/resolver:
        node:
            extensions:
                - ".ts"
                - ".tsx"